### ISSUE TITLE
Dotmailer IPs in IP Restrictions Admin Setting is outdated

### ISSUE THREAD

**Issue by technik-vitafy** [dotmailer/dotmailer-magento-extension#11]
We have currently production issues since the IP Addresses seem to be outdated:

            <ip_restriction>
                <ip_addresses>94.143.111.2, 94.143.111.3</ip_addresses>
            </ip_restriction>

Could you please provide us with the new ip address list?

**Comment by cdiacon** [comment]
@technik-vitafy this should be the correct ip's, what is the exact issue?

**Comment by technik-vitafy** [comment]
This is the stacktrace plus error message:

You are not authorised to view content of this page.

Trace:
#0 /opt/magento/.modman/dotmailer-magento-extension/code/Dotdigitalgroup/Email/controllers/EmailController.php(32): Dotdigitalgroup_Email_ResponseController->authenticate()
#1 /opt/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Dotdigitalgroup_Email_EmailController->couponAction()
#2 /opt/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('coupon')
#3 /opt/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#4 /opt/magento/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#5 /opt/magento/htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#6 /opt/magento/htdocs/index.php(115): Mage::run('', 'store')
#7 {main}

**Comment by cdiacon** [comment]
Is this when you actually try to send a campaign or this is the result of your local url test?

**Comment by technik-vitafy** [comment]
That applies in our case to dynamic content requests for coupons.

**Comment by cdiacon** [comment]
If you want to test coupons you'll have to add your IP, but this is restricted to dotmailer api access only.

So all you have to do is to add your local IP to the list Developer -> Dynamic Pages IP Restriction list.
