### ISSUE TITLE
Order Connector generates errors using strlen() function

### ISSUE THREAD

**Issue by equinoxmatt** [dotmailer/dotmailer-magento-extension#12]
Hello,

Quite minor issue,  but is still filling up our logs with PHP warnings.

> ERR (3): Warning: strlen() expects parameter 1 to be string, array given

[Line 288](https://github.com/dotmailer/dotmailer-magento-extension/blob/master/code/Dotdigitalgroup/Email/Model/Connector/Order.php#L288)

    protected function _limitLength($value)
    {
        if (strlen($value) > 250)
            $value = substr($value, 0, 250);
        return $value;
    }

The function does not check if $value is an array.

**Comment by cdiacon** [comment]
@equinoxmatt thanks will fix this, can you share the product attribute name which caused this?

**Comment by equinoxmatt** [comment]
Hi @cdiacon 

We seem to have a few,  not sure if this is specific to our installation:

'tier_price'
'promoid'
'gift_message_available'
'p_finish'
'tax_class_id'

**Comment by cdiacon** [comment]
For input types:  'multiselect', 'select', 'dropdown' it returns the attribute text so not these which are default 
gift_message_available - select
tax_class_id - select
