### ISSUE TITLE
Load appcues script on extension pages only

### ISSUE THREAD

**Issue by adeelq** [dotmailer/dotmailer-magento-extension#130]
Instead of loading appcues script on all pages on backend only to load the script on extension pages

**Comment by cdiacon** [comment]
Getting this when updated to the latest : 
![Uploading Screen Shot 2016-10-07 at 12.39.00.png…]()

**Comment by adeelq** [comment]
Strange it is running canRunScript function on Mage_Core_Block_Template instead of running this function from class Dotdigitalgroup_Email_Block_Adminhtml_System_Appcues

Cache clearing needed maybe?

**Comment by adeelq** [comment]
Works fine for me..can you tell me which testing site this in

**Comment by aliomattux** [comment]
I know this is a closed issue, but I had exactly the same problem. The only way around it was to remove this code from the admin html, do a full cache clear and then log back in. Removing cache files from the filesystem and restarting redis wasn't enough
