### ISSUE TITLE
Easy email capture loading non-secure content on https websites

### ISSUE THREAD

**Issue by dotZygis** [dotmailer/dotmailer-magento-extension#138]
Easy email capture loading non-secure content on https websites.
Easy email capture loading secure content on http websites too.

**Comment by cdiacon** [comment]
Is this using always https or a mixed @dotZygis, can you put more info on this one? 

Also, this issue may go to the 3'rd party module https://github.com/mailcheck/mailcheck
cc @adeelq

**Comment by dotZygis** [comment]
@cdiacon This is always using secure URL. We should first validate if the website is secure or not. Only then we grab the base url.
