### ISSUE TITLE
Two entries in subscriber table when guest subscriber becomes customer

### ISSUE THREAD

**Issue by dotZygis** [dotmailer/dotmailer-magento-extension#144]
Duplicate customer entries can be created by doing the following:

Subscriber as a guest.
Register a new account with the same email account.

Result: two entries are created in our table.

**Comment by cdiacon** [comment]
@dotZygis you can't have multiple contact records for same website_id, what is rest of the data for these contacts??

**Comment by dotZygis** [comment]
@cdiacon one is customer with full info, another one is guest with website_id and email. Both from the same website. I'm attaching a screenshot.
![screenshot_124](https://cloud.githubusercontent.com/assets/20168523/19891757/74d53a96-a039-11e6-80ff-cde8e42f918c.png)

**Comment by adeelq** [comment]
@cdiacon @dotZygis so i tried it as well and i was able to replicate it same as zygi

so here $emailBefore is empty which results in creating duplicate entry by function loadByCustomerEmail in class Dotdigitalgroup_Email_Model_Contact 

https://github.com/dotmailer/dotmailer-magento-extension/blob/master/code/Dotdigitalgroup/Email/Model/Customer/Observer.php#L33

empty $emailBefore creates query

    SELECT `main_table`.* FROM `email_contact` AS `main_table` WHERE (`email` = '') AND (`website_id` = '1')
