### ISSUE TITLE
Improved Importer

### ISSUE THREAD

**Issue by bsstaveley** [dotmailer/dotmailer-magento-extension#15]
This is making alterations to improve 2 things, adding priority to contacts syncing as this is the most valuable data to a merchant. And allowing multiple bulk syncs to occur at the same time to improve performance with large or multi website instances.

**Comment by cdiacon** [comment]
assigning this is confusing : 

$order = $contact;
$quote = $other = $order;
$quoteUpdate = $orderUpdate;

maybe having the $default data for bulk and for singles and then overwrite as we need will be better.

**Comment by cdiacon** [comment]
1. not a valid camel case for a function _csv_to_array, _remove_utf8_bom.
2. use Varien_Io_File (streamReadCsv) helpers to manage csv files.
3. Mage::getModel($single['model'], $collection) - run sync in constructor is bad idea, no way to trace errors.

**Comment by cdiacon** [comment]
This should be evaluated to bool/num not empty
```
//singles
if(empty($this->_totalItems)){
```
Also 
this condition means that in case when bulk is created every 5min the single imports will never run?

**Comment by cdiacon** [comment]
4 . constructor override not needed 
https://github.com/dotmailer/dotmailer-magento-extension/pull/20/commits/0bf40e5cceae568ef763bc784a0400cc2837c1fc#diff-831200209da1b9c8a812d28ad5b00becR5

5 . $result may not be defined 
https://github.com/dotmailer/dotmailer-magento-extension/pull/20/commits/0bf40e5cceae568ef763bc784a0400cc2837c1fc#diff-6f6a74367bf3f90f27c55447d7b64b63R53

**Comment by adeelq** [comment]
@cdiacon Thanks looking into all

**Comment by cdiacon** [comment]
6. Mode is the same as the key and for other source is not. The label should be readable, ex Single Delete not Single_Delete

https://github.com/dotmailer/dotmailer-magento-extension/blob/b9d5a282741d744b91060a9388bbc9db7392c892/code/Dotdigitalgroup/Email/Model/Adminhtml/Source/Importer/Mode.php

https://github.com/dotmailer/dotmailer-magento-extension/blob/b9d5a282741d744b91060a9388bbc9db7392c892/code/Dotdigitalgroup/Email/Model/Adminhtml/Source/Importer/Status.php
