### ISSUE TITLE
RayLog exception when running `ddg_automation_importer` cron service

### ISSUE THREAD

**Issue by shanelja** [dotmailer/dotmailer-magento-extension#150]
Since upgrading to version 6.2.1 of the Dotmailer Magento extension, any attempts to run the ddg_automation_importer cron fail with the following message: `TRIGGER: shutdown function`

If we run the cron manually using n98-magrun.phar, as such `shell/n98-magerun.phar sys:cron:run ddg_automation_importer`, we can trigger the following error:

`PHP Fatal error:  Call to undefined method Dotdigitalgroup_Email_Helper_Data::rayLog() in $MAGENTO_PATH/app/code/community/Dotdigitalgroup/Email/Model/Apiconnector/Client.php on line 885`

We have no overloaded module files, are running on PHP 5.5.21 using PHP-55-FPM on RHEL6.

**Comment by dotZygis** [comment]
Hello Shane,

We are aware of this issue in 6.2.1. We have released 6.2.2 where the issue is fixed. Would you be comfortable upgrading?

**Comment by shanelja** [comment]
Thanks @dotZygis, I'll test the new version and close this ticket if the issue is resolved.

**Comment by shanelja** [comment]
@dotZygis I can confirm that upgrading from 6.2.1 to 6.2.2 fixes the Raygun exception issues, thanks.
