### ISSUE TITLE
Improve order sync

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento-extension#186]
Orders sync becomes problematic when the contact is not imported/exists into account. Also there are not enough options to customize the sync. Order sync should do : 

1. Look for a contact imported(should be marked as imported in email_contat table)
2. Import oldest first (should import historical orders first)
3. Disable the order sync when getting the JsonValueIncompatibleWithSchema error. (Orders collection should be removed)
4. Mapping new custom attributes should reset sync?!?
5. Increase the order bulk during particular hours(night time)
6. Add new option for 1000 and 1500 orders.
7. Remove product attributes from the options that is syncing by default.(ex.product-name..)
8. Attribute object is included into the sync is the product has attribute set enabled (unset _attributeSet from sync.)
9. Set the Message with time remain for order to be imported(because of the delay 1h).

**Comment by cdiacon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve order sync](https://trello.com/c/Fu9wh7nq/647-improve-order-sync)

**Comment by adeelq** [comment]
@cdiacon for point 5 we should have config TD Night Limit and i think we should do this for all TD sync types
