### ISSUE TITLE
Connector status is giving a Notice Undefined index:

### ISSUE THREAD

**Issue by anuradha** [dotmailer/dotmailer-magento-extension#187]
We are getting the the Notice when I browse the Marketing Automation->Dashboard->Connector Status.
This is not fixed yet in Dotmailer >= 6.2.2.

`​Notice: Undefined index: lib in app/code/community/Dotdigitalgroup/Email/Block/Adminhtml/Dashboard/Tabs/Status.php on line 433`

`app/code/community/Dotdigitalgroup/Email/Block/Adminhtml/Dashboard/Tabs/Status.php(433): mageCoreErrorHandler(8, 'Undefined index...', '/var/www/html/b...', 433, Array)`

fix:
Path: app/code/community/Dotdigitalgroup/Email/etc/files.yaml (#241)​

```
lib:
  - connector#feefo#feedback.xsl
  - connector#feefo#feedback-no-th.xsl
```

Thanks

**Comment by cdiacon** [comment]
@anuradha thanks for sending this but feefo it's been removed in 6.2.5

https://github.com/dotmailer/dotmailer-magento-extension/commit/98015c7f0391226c3fb1600d43e85b488937ab95

**Comment by anuradha** [comment]
@cdiacon noted. but you should have define lib path in files.yaml. correct?
