### ISSUE TITLE
Abandoned cart with wrong email_contact_id #

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento-extension#188]
Guest Subscriber sync datafields will populate the wrong email_contact_id for the contacts which is used to send abandoned carts. This will be used to send abandoned carts which don't exist in account : 

Will result in error messages like : 

```
One or more of the supplied contacts were not found. Send not permitted. ERROR_CONTACT_NOT_FOUND
```

```
contact id returned is not numeric for email 
```

**Comment by adeelq** [comment]
Same as this https://github.com/dotmailer/dotmailer-magento2-extension/issues/202

contact id returned is not numeric for email https://github.com/dotmailer/dotmailer-magento-extension/issues/189
