### ISSUE TITLE
Performance issue with Collection at Dotdigitalgroup_Email_Model_Adminhtml_Observer

### ISSUE THREAD

**Issue by somep1xel** [dotmailer/dotmailer-magento-extension#2]
Hello!

We have faced with performance issue, tied with using of Magento collection in [Dotdigitalgroup_Email_Model_Adminhtml_Observer](https://github.com/dotmailer/dotmailer-magento-extension/blob/master/code/Dotdigitalgroup/Email/Model/Adminhtml/Observer.php) class.

Code below creates Collection based on big amount of entries that significantly affect overall performance of server CPU. This happens for all unlogged users (case when $customerId is empty). 
```javascript
protected function addContactsFromWebsiteSegments($customerId, $segmentIds, $websiteId){
...
$contact = Mage::getModel('ddg_automation/contact')->getCollection()
            ->addFieldToFilter('customer_id', $customerId)
            ->addFieldToFilter('website_id', $websiteId)
            ->getFirstItem();
...
```

Function addContactsFromWebsiteSegments() had been added at [V4.0.0 release] (https://github.com/dotmailer/dotmailer-magento-extension/blame/master/code/Dotdigitalgroup/Email/Model/Adminhtml/Observer.php#L209).

Best practice from Magento is to divide collection into pages (using method setPageSize()) or to limit number of selected rows.

So we have made changes below to solve performance issue:
```javascript
$contact = Mage::getModel('ddg_automation/contact')->getCollection()
            ->addFieldToFilter('customer_id', $customerId)
            ->addFieldToFilter('website_id', $websiteId)
            ->setPageSize(1)
            ->getFirstItem();
```
Please let me know if it may somehow affects plugin's functionality.

Thanks,
Maxim.

**Comment by cdiacon** [comment]
Hi Max,

Just to make clear what is happening here, the segments needs to update our contact with id's. So we have the relation of customer and contact one to one, this way you should never receive more then one record for a customer for a specific website id.

The performance issue you found is that the customer id will be null for guests, and we don't have customer segments id's for guest.

```
$segmentsIds = $observer->getEvent()->getSegmentIds();
$customerId = Mage::getSingleton('customer/session')->getCustomerId();

$websiteId = Mage::app()->getStore()->getWebsiteId();

if (!empty($segmentsIds && $customerId)) {
	$this->addContactsFromWebsiteSegments($customerId, $segmentsIds, $websiteId);
}
``` 

should fix the issue.

**Comment by somep1xel** [comment]
Hey!
Yes, it helps. Thanks for quick response!

**Comment by cdiacon** [comment]
No problem, this will be published in the next release.
I'll close the ticket for now.

Uda4i.
