### ISSUE TITLE
ddg_automation_customer_subscriber_guest_sync cron putting too much load on server

### ISSUE THREAD

**Issue by zainsohail88** [dotmailer/dotmailer-magento-extension#200]
We have recently updated Dotmailer extension from version **6.1.0** to **6.2.5**
There are few issues which we encountered after upgrade but one of them is most important and is causing too much load resulting in site to become unresponsive.

## The problem: 
**ddg_automation_customer_subscriber_guest_sync** cron is putting too much load on server.

I originally thought it was happening due to large number of contact we had but after setting all contacts as imported by running following query:

`UPDATE email_contact SET email_imported=1 WHERE email_imported IS NULL`

The problem is still present, so i check Sync Size Limits which are currently set to:
Contact Sync Size: 100
Data Sync Size: 50

Further investigation show that below listed queries are taking alot of time:

```SELECT `main_table`.* FROM `sales_flat_order` AS `main_table` WHERE (`customer_email` IN(NULL));```

```SELECT `main_table`.* FROM `email_contact` AS `main_table` WHERE (`is_subscriber` IS NOT NULL) AND (`subscriber_imported` IS NULL) AND (`store_id` IN('0')) AND (`customer_id` != 0) LIMIT 100;```

```SELECT SUM(IFNULL(main_table.base_total_invoiced, 0) - IFNULL(main_table.base_tax_invoiced, 0) - IFNULL(main_table.base_shipping_invoiced, 0) - (IFNULL(main_table.base_total_refunded, 0) - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0)))/count(*) AS `customer_average_order_value` FROM `sales_flat_order` AS `main_table` WHERE (`status` NOT IN('canceled')) AND (`state` NOT IN('new', 'pending_payment')) AND (main_table.customer_id != 'null') GROUP BY `customer_id` ORDER BY `customer_average_order_value` ASC;```

## P.S: 

I have disabled the crons for now and running the import manually also causes same problem.

Please review and feel free to contact me if you need further information.
I will look forward to a fix for this as soon as possible.

Thank You

**Comment by adeelq** [comment]
@zainsohail88 For this query you can apply below commit. However this query will not return any result because of WHERE (`customer_email` IN(NULL)) so there should not be any load on server because of this. Please run this query directly in mysql database to see the result and the time it takes

    SELECT `main_table`.* FROM `sales_flat_order` AS `main_table` WHERE (`customer_email` IN(NULL));

Please apply this commit https://github.com/adeelq/dotmailer-magento-extension/commit/dcfa120715299299e7caba08690feb99639209b8?diff=unified 

This query also should not put any load on server. The only field does not have index on is store_id. Even without index on store_id there is limit of 100. Please run this query directly in mysql database to see the result and the time it takes

    SELECT `main_table`.* FROM `email_contact` AS `main_table` WHERE (`is_subscriber` IS NOT NULL) AND (`subscriber_imported` IS NULL) AND (`store_id` IN('0')) AND (`customer_id` != 0) LIMIT 100;

This query is not part of any cron job. This query only runs when you load our Dashboard. This comes from https://github.com/dotmailer/dotmailer-magento-extension/blob/master/code/Dotdigitalgroup/Email/Model/Resource/Contact.php#L245  
This query can be heavy depending on data size. However this does not effect the performance of cron jobs running. This query will only run when you visit our Dashboard page.

    SELECT SUM(IFNULL(main_table.base_total_invoiced, 0) - IFNULL(main_table.base_tax_invoiced, 0) - IFNULL(main_table.base_shipping_invoiced, 0) - (IFNULL(main_table.base_total_refunded, 0) - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0)))/count(*) AS `customer_average_order_value` FROM `sales_flat_order` AS `main_table` WHERE (`status` NOT IN('canceled')) AND (`state` NOT IN('new', 'pending_payment')) AND (main_table.customer_id != 'null') GROUP BY `customer_id` ORDER BY `customer_average_order_value` ASC;

**Comment by zainsohail88** [comment]
Thank You @adeelq for quick reply.
I am going to apply suggested changes and will keep you posted as things progress.

**Comment by zainsohail88** [comment]
Hi @adeelq 
Please find the execution time for each query directly from SQL below.
I am going to apply the commit changes and will keep you posted as things progress.

```SQL
SELECT `main_table`.* FROM `sales_flat_order` AS `main_table` WHERE (`customer_email` IN(NULL)); 
# 59.807 sec

SELECT `main_table`.* FROM `email_contact` AS `main_table` WHERE (`is_subscriber` IS NOT NULL) AND (`subscriber_imported` IS NULL) AND (`store_id` IN('0')) AND (`customer_id` != 0) LIMIT 100; 
# 3.734 sec

SELECT SUM(IFNULL(main_table.base_total_invoiced, 0) - IFNULL(main_table.base_tax_invoiced, 0) - IFNULL(main_table.base_shipping_invoiced, 0) - (IFNULL(main_table.base_total_refunded, 0) - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0)))/count(*) AS `customer_average_order_value` FROM `sales_flat_order` AS `main_table` WHERE (`STATUS` NOT IN('canceled')) AND (`state` NOT IN('new', 'pending_payment')) AND (main_table.customer_id != 'null') GROUP BY `customer_id` ORDER BY `customer_average_order_value` ASC;
# 6.028 sec
```

Please feel free to contact me if you have any question or comment.

Thank You

**Comment by zainsohail88** [comment]
**UPDATE:** this https://github.com/adeelq/dotmailer-magento-extension/commit/dcfa120715299299e7caba08690feb99639209b8?diff=unified didn't have any improvements on performance. We are still facing the load issues.

**Comment by adeelq** [comment]
@zainsohail88 This issue seems like more suitable for support. Please create a support ticket https://support.dotmailer.com/hc/en-gb

**Comment by adeelq** [comment]
@zainsohail88 So we found issues for your problem. Please see commits in this issue and apply all of them. Please do let me know if this solves your problem. 
https://github.com/dotmailer/dotmailer-magento-extension/issues/211

**Comment by adeelq** [comment]
@zainsohail88 from the issue i mentioned please apply only two following commits. This should fix server load problem. There were few places we were not checking if array is empty or not before using in collection filter IN clause. 

https://github.com/cdiacon/dotmailer-magento-extension/commit/7a9144e9fa05998647537ec98f44c3f7c0e4ce22

https://github.com/cdiacon/dotmailer-magento-extension/commit/d9bdfccc0600b688314212b7cdbf5103a0133d89

**Comment by zainsohail88** [comment]
Hi @adeelq 

Unfortunately the suggested change sets didn't fix the problem, the cron `ddg_automation_customer_subscriber_guest_sync` has been running from past 40+ minutes

![magento admin](https://cloud.githubusercontent.com/assets/3738633/23673609/b888abe2-0394-11e7-853e-687eaec9e6b9.png)

Also one more thing i noticed was *Marketing Automation Log* shows following file names: 

- Subscriber filename: base_subscribers_07_03_2017_1837.csv
- Subscriber file with sales : ardene_usa_subscribers_with_sales_07_03_2017_1837.csv
- Subscriber filename: ardene_usa_subscribers_07_03_2017_1837.csv

but these files do not exist on server under `var/export/` folder, could this be causing problem?

Please let me know.

Thank You
