### ISSUE TITLE
Update contacts with customers that are subscribers

### ISSUE THREAD

**Issue by adeelq** [dotmailer/dotmailer-magento-extension#220]
Update contacts with customers that are subscribers part of script where cross update on join is taking too much time to complete 

https://github.com/dotmailer/dotmailer-magento-extension/blob/6df0aab6afb170f37da0729aa136263434fabc1d/code/Dotdigitalgroup/Email/sql/email_connector_setup/mysql4-install-6.0.0.php#L435-L453

**Comment by mcspronko** [comment]
Hi @adeelq 

Do you plan to have fix for Magento 2 version of DotMailer?

Thanks.

**Comment by adeelq** [comment]
Hi @mcspronko Fix for Magento 2 will be ready the end of this month.
