### ISSUE TITLE
Number of items to display for "Related Products" is incorrect 

### ISSUE THREAD

**Issue by dotZygis** [dotmailer/dotmailer-magento-extension#241]
If the number of items to display is set to 4 then the EDC only displays 2 products. However if I move this to 6 it displays 4 so on and so on.  It never displays the proper amount of items. 

This can only be replicated when there are multiple products in the quote (more than 1).

**Comment by adeelq** [comment]
@dotZygis cannot replicate this. I tried all what you described above.
