### ISSUE TITLE
Visibility column not found for bestsellers

### ISSUE THREAD

**Issue by dotZygis** [dotmailer/dotmailer-magento-extension#249]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.visibility' in 'where clause'

https://github.com/dotmailer/dotmailer-magento-extension/blob/master/code/Dotdigitalgroup/Email/Block/Edc.php#L278

'visibility' column doesn't exist for some customers. This issue only applies to bestsellers.

**Comment by cdiacon** [comment]
related https://github.com/dotmailer/dotmailer-magento-extension/issues/254
