### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by chesuch** [dotmailer/dotmailer-magento-extension#276]
`Notice: Trying to get property of non-object in /var/www/vhosts/betterbathrooms.com/production/htdocs/app/code/community/Dotdigitalgroup/Email/Block/Customer/Account/Books.php on line 228`

It seems from within the newsletter subscription section of your account, where the following code retrieves no object,  
```
$contact = $this->_getApiClient()->postContacts(
    $this->getCustomer()->getEmail()
);
```

the following line results in the above error. 
`if ($contact->id) {`

I can do a local override to resolve as it is having an impact on our logs, but could this perhaps be addressed in a future release e.g.

as per line 221
`if (isset($contact->id)) {`

**Comment by simon-letch** [comment]
Hey chesuch,

We've fixed this as part of the following commit: https://github.com/dotmailer/dotmailer-magento-extension/commit/8e8a4627e798327dc3af320ca48f11d0c0b2916c and it was released as part of v6.3.4.

I'm going to mark this as closed now.

Simon
