### ISSUE TITLE
duplicate abandoned basket emails

### ISSUE THREAD

**Issue by cwpm** [dotmailer/dotmailer-magento-extension#277]
There are issues with the Abandoned Basket e-mails queuing and sending duplicates.

The Magento cron is scheduled for every 5 minutes; however if the job is delayed it might not run due to other jobs in the cron execution queue taking longer to run.

Which means it can end up stacking up and running a later date. Often with three e-mails are being received with only seconds between them, as they will all run simultaneously on the 3rd cron queue due to the stacking.

What should happen is to send emails for the abandoned baskets 5 minutes prior to the schedule time of the cron task; but instead they are being sent emails 5 minutes prior to the current time of the job running.

The dotmailer code responsible is:

$from->sub('5', Zend_Date::MINUTE);

The offending line is still in exiting version... Can this be updated to prevent the issue?

**Comment by simon-letch** [comment]
Hey cwpm,

Yes, this looks like a problem. As a workaround for now, you can set the abandoned cart limit described in this support article: https://support.dotmailer.com/hc/en-gb/articles/216279898-Getting-started#adjustacelimit

The limit has the effect of preventing any further abandoned cart emails being sent within that period. So make sure you set it less than your AC2 email, or it will block that from being sent.

We are currently reworking our abandoned cart offering and i'll make sure this gets addressed at the same time.

Thanks,
Simon

**Comment by cwpm** [comment]
Hi there,

Can you confirm if this change has now in a release version (or the one released few hours ago)? The task is closed but it's not clear where it is now.

Thank you for the previous information, it mitigated the issue slightly and didn't occur as much but looking forward to upgrading soon as to finally get rid of it completely.

**Comment by cdiacon** [comment]
Hi @cwpm,
You can use the V.6.3.5 there a new way to send abandoned carts that should stop sending duplicates.
