### ISSUE TITLE
Adding ability to control functions to display including or excluding VAT

### ISSUE THREAD

**Issue by cwpm** [dotmailer/dotmailer-magento-extension#279]
We've had numerous requirements for builds that use Dotmailer where depending on the products and setup of the costs of each product is to display as excluding or including VAT for Recently Viewed, Abandoned, Best Seller, etc.

The products themselves are set as excluding VAT but need VAT adding to them for the AB, Recently Viewed, etc. These changes are needed to be made to the phtml files in order to get them to display correctly which of course on any upgrade needs to be re-done. 

Can a function be added to the module to allow an option to choose to display Ex VAT or Inc VAT prices for products? A general overall should be fine than the individual type of output (e.g. AB, Best seller).

**Comment by cdiacon** [comment]
Hi @cwpm, 
Thanks for sending this over can you please submit as a feature request on our community forum

https://support.dotmailer.com/hc/en-gb/community/topics/200432508-Feedback-and-feature-requests

**Comment by cwpm** [comment]
Submitted, thank you.
