### ISSUE TITLE
 Exclude Developers IPs from Abandoned Basket

### ISSUE THREAD

**Issue by obsergiu** [dotmailer/dotmailer-magento-extension#280]
We were extending the old module in order to exclude the developer IPs from abandon cart based on qoute remote_ip.

But I think that's a good functionality, would you consider to add it to your module?
Say: ignore developers ips as we did or provide a field where to add what IP we want to ignore for abandon cart. This is also beneficial for statistic purpose. 

Thanks

**Comment by cdiacon** [comment]
Hi @obsergiu 

you can check the docs here how you can set up the developer IP restriction for all Dynamic pages 

https://support.dotmailer.com/hc/en-gb/articles/216282318-Security-settings

let me know if this helps,

Calin.

**Comment by obsergiu** [comment]
Hello @cdiacon 

Thanks for fast feedback.
I know about the field  from
  ```
System > Dotmailer >  Developer > Dynamic Pages IP Restriction
``` 
but my request is a bit different, you see when you trigger an abandon  cart the ip's from that field are not checked agains ```remote_ip``` from  abandon **quote**.

Essentially you have 2 functions which are getting the info from ```sales_flat_quote``` which are **getAbandonedCartsForStore()** and **getStoreQuotes()**.

In both of them you'll find this call:

```
$abandoneCollection = Mage::getModel('ddg_automation/abandoned')
            ->getCollection()
            ->addFieldToFilter('is_active', 1)
            ->addFieldToFilter('abandoned_cart_number', --$number)
            ->addFieldToFilter('store_id', $storeId)
            ->addFieldToFilter('quote_updated_at', $updated);
```

What I suggest is to add one more filter, like : 

```
        ->addFieldToFilter('remote_ip', array('neq' => $officeIP))
``` 

Where **$officeIP** can be taken from **Dynamic Pages IP Restriction** field

**Comment by cdiacon** [comment]
@obsergiu did you try to set the Exclusion rules for Abandoned carts, you can't use IP restriction but I am sure you can use "testing" email addresses for ex. and create a rule to not send Abandoned carts and keep the statistics clean?!?

https://support.dotmailer.com/hc/en-gb/articles/216282008-Exclusion-rules

**Comment by obsergiu** [comment]
@cdiacon thank you for suggestion.
It's a great feature but unfortunately we have a couple departments (content, sales..) which are placing orders on our live website  and we tried multiple solutions but in the end  we come up with the idea of just excluding the IP as we're not sure what emails they would use.

I will notify everybody and try to use the 'test' email exclusion rule, hopefully will reach a better result. 

Though would be great to have in that drop down the "Remote IP" option.

Thank you Calin
