### ISSUE TITLE
Missing index for slow queries

### ISSUE THREAD

**Issue by igorwulff** [dotmailer/dotmailer-magento-extension#286]
We have been working with the dotmailer extension for a while. We now notice two slow queries because of indexes not covering the entire select. The queries are:

`SELECT `main_table`.* FROM `email_contact` AS `main_table` WHERE (`is_subscriber` IS NOT NULL) AND (`subscriber_imported` IS NULL) AND (`store_id` IN(?, ?)) AND (`customer_id` != ?) LIMIT ? `

This one uses the index subscriber_imported field, but if the remaining dataset is really large it is still a heavy query. And becomes almost a full table scan. In our case more then 1 million records are traversed, depending on the size of the email_contact table and the WHERE case.

-----

` SELECT COUNT(*) FROM `email_contact` AS `main_table` WHERE (`is_guest` IS NOT NULL) AND (`email_imported` IS NULL) AND (`website_id` = ?) `

This index uses IDX_EMAIL_CONTACT_EMAIL_IMPORTED,IDX_EMAIL_CONTACT_WEBSITE_ID, but still has to check if is_guest IS NOT NULL from the result it gets. This one is less important, but can sometimes be heavy. Not entirely sure how big an improvement adding a field to the index or creating a new index with the combination of fields adds.

**Comment by cdiacon** [comment]
@igorwulff thanks for sending this over.

Just want to make sure that the actual index is not missing, but would be great to have a combination of more then one index for big data query?

**Comment by igorwulff** [comment]
Hi @cdiacon,

Sorry about my late response because of my own holiday. An actual index is indeed in place and used for the selects, we think it should however be more specific. So yes, this is solely a problem for bigger datasets.

**Comment by cdiacon** [comment]
@igorwulff not a problem at all.

Do you have the timings for this query :
SELECT COUNT(*) FROMemail_contactASmain_tableWHERE (is_guestIS NOT NULL) AND (email_importedIS NULL) AND (website_id= ?)

Also, you mentioned about more than a million, can I get the exact number, please?

I'll have a look and see if there any improvement to add more indexes.

**Comment by igorwulff** [comment]
@cdiacon I will try to give you more info tomorrow.

**Comment by igorwulff** [comment]
There are 2,149,863 records in email_contact.

The COUNT(*) query as specified is not as big of a problem, but an index might improve some of the selection. Currently it will scan 86137 rows. With a key of 
IDX_EMAIL_CONTACT_EMAIL_IMPORTED,IDX_EMAIL_CONTACT_WEBSITE_ID using an index merge. 

I don't have the timings at hand at the moment, but it takes a second or so. If you need more specifics I can provide them later on.

**Comment by sta1r** [comment]
@igorwulff Apologies - this issue has been sitting for a while. 

Our usual recommendation to merchants with larger datasets requesting additional indexes (beyond those already defined - and all but one of the fields in `email_contact` has an index already) is to experiment with multi-column indexes on duplicate tables, and to implement these themselves if they are effective.

As a rule, we wouldn't add these to our install scripts, lest they reduce write speed for other customers.
