### ISSUE TITLE
Cron ddg_automation_customer_subscriber_guest_sync executing while disabled

### ISSUE THREAD

**Issue by adamlavery** [dotmailer/dotmailer-magento-extension#290]
The ddg_automation_customer_subscriber_guest_sync cron task continues to execute and, if unconfigured, generate regular cron errors while the module is disabled. Nothing should run if the module is disabled, including the other DDG cron tasks which are still scheduled when disabled.

This behaviour is seen in both M1 and M2.

**Comment by cdiacon** [comment]
Hi @adamlavery,

Thanks for sending this and I agree that this is the case for M2 which you can find more information  here : https://github.com/dotmailer/dotmailer-magento2-extension/issues/495

Closing the issue as cannot be reproduced on M1.
