### ISSUE TITLE
Unable to view Extension Version via Magento Admin

### ISSUE THREAD

**Issue by davidedmonson** [dotmailer/dotmailer-magento-extension#298]
It would be helpful to store owners and administrators to view the extension version within the Magento admin within the Configuration or Developer tabs of the Dotmailer Extension settings.

**Comment by ab-ivanov** [comment]
Hi Davide,
If I'm understanding you question correctly you can see the dotmailer magento extension version in the admin at **Marketing  Automation > Dashboard > Connector Status > System Information**  where **Connector version : V6.4.3**  is the extension version
