### ISSUE TITLE
unserialize sometimes causes a notice.

### ISSUE THREAD

**Issue by mediact-pipelines** [dotmailer/dotmailer-magento-extension#299]
In the following classes:
Dotdigitalgroup_Email_Model_Sync_Td_Bulk
Dotdigitalgroup_Email_Model_Sync_Contact_Delete
Dotdigitalgroup_Email_Model_Sync_Td_Delete
Dotdigitalgroup_Email_Model_Sync_Td_Update
Dotdigitalgroup_Email_Model_Sync_Contact_Update

the function 'unserialize' is being used. However if the param being given is not a correct serializable string it will trigger a notice.

It would be better to use @unserialize and check if the return value is false. If false don't continue with the rest of the code and log the issue.

**Comment by sta1r** [comment]
Hi @mediact-pipelines - apologies, this is rather an old issue. 

We could add some code to handle unserializable import data, although perhaps the root issue is:  how or why is the data stored in `email_importer` not "correct"?
