### ISSUE TITLE
Problem with member sync - Table prefixes?

### ISSUE THREAD

**Issue by kush1960** [dotmailer/dotmailer-magento-extension#3]
Hi, I'm having the following error when running the subscriber sync manually...
```a:5:{i:0;s:295:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pexwhole_magento_staging.newsletter_subscriber' doesn't exist, query was: UPDATE `p3x_email_contact` AS `c`
 LEFT JOIN `newsletter_subscriber` AS `s` ON c.customer_id = s.customer_id
SET `c`.`subscriber_status` = `s`.`subscriber_status`";i:1;s:2709:"#0 /chroot/home/pexwhole/staging.pexwholesale.co.uk/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)```
It appears that it's looking up a default table name, whereas my installation uses prefixes... p3x_

**Comment by bsstaveley** [comment]
Hi @kush1960 can you confirm the version you have installed of our extension please?

**Comment by kush1960** [comment]
@bsstaveley it's version 5.1.0 installed by Magento Connect.

**Comment by cdiacon** [comment]
Hi @kush1960, this should't happen and I can see the prefix is used for "p3x_email_contact" same used for other resource table. Can you reset the installer by removing the core_resource record "email_connector_setup" and see if you get the same message?

**Comment by kush1960** [comment]
Hi @cdiacon It looks like Im running  V5.0.4 after all. Removing that entry from the DB didn't fix it. I'm going install the latest version from Github to see if that fixes things.

**Comment by kush1960** [comment]
Egg on my face... this is working fine in 5.1.0. Sorry.
