### ISSUE TITLE
Unsafe Use of Curl Options: Verify Peer Disabled

### ISSUE THREAD

**Issue by ajbonner** [dotmailer/dotmailer-magento-extension#302]
Setting this to false, exposes users to potential Man in the Middle Attacks.

https://github.com/dotmailer/dotmailer-magento-extension/blob/master/code/Dotdigitalgroup/Email/Model/Apiconnector/Client.php#L213

As far as I can see the API endpoints have valid ssl certificates and validation chains so  unless there's a strong case, this setting should be hardened.

**Comment by sta1r** [comment]
Released in https://github.com/dotmailer/dotmailer-magento-extension/releases/tag/v6.4.18
