### ISSUE TITLE
Magento 2.3-beta MFTF tests fails

### ISSUE THREAD

**Issue by magicsunday** [dotmailer/dotmailer-magento-extension#306]
The Magento 2.3-beta32 MFTF (using latest magento/magento2-functional-testing-framework release) tests fails with the following error:

Parameter Resolution Failed: No parameter matches found in parameterized element with selector connector/email/basket/code.
  Exception occurred parsing action at StepKey "amOnAbandonedCartPage" in Test "AbandonedCartUrlLockedTest"
  /vendor/dotmailer/dotmailer-magento2-extension/Test/Mftf/Test/AbandonedCartLockedTest.xml

**Comment by TrGlen** [comment]
@magicsunday thanks for reporting this.
This issue seems to be related to our M2 extension. Could you open this issue [here ](https://github.com/dotmailer/dotmailer-magento2-extension/issues) instead?

Thanks,
Tristan

**Comment by simon-letch** [comment]
This will be fixed in our next release.

I'm going to close this issue.
