### ISSUE TITLE
Improper implode syntax

### ISSUE THREAD

**Issue by danmentzer** [dotmailer/dotmailer-magento-extension#309]
I believe i had a support ticket with dotmailer previously about this issue.
Just pulled the latest release from the repo.
app/code/community/Dotdigitalgroup/Email/Model/Connector/Order.php

`Line 536                                 $value = implode($value, ', ');
 `

That line should be 
`                                $value = implode(',',$value);
`

I came across this while reviewing the latest release 6.4.11.

**Comment by adeelq** [comment]
@danmentzer Thanks for reporting this. We have added this to out current sprint. Will update you when it is released.

**Comment by adeelq** [comment]
This is now release in latest version.
