### ISSUE TITLE
Calls to utf8_decode causing empty subject and no sender name

### ISSUE THREAD

**Issue by Obblesnatch** [dotmailer/dotmailer-magento-extension#310]
Hello,

We recently updated from version 6.3.7 to 6.4.11 and have noticed a problem.

In the file app/code/community/Dotdigitalgroup/Email/Block/Adminhtml/Column/Renderer/Template.php
utf8_decode is wrapped in an 'if' that checks first if the template is from Dotdigital.
However elsewhere in the code utf8_decode is called without checking if the template is from Dotdigital. This breaks the value and causes the subject and sender name to be empty.

We wrapped these other calls to utf8_decode in the same if and it corrected the problem. The two other instances are in:
**app/code/community/Dotdigitalgroup/Email/Model/Email/Template.php Line 158**
**app/code/community/Dotdigitalgroup/Email/Model/Adminhtml/Email/Template.php Line 13**

**Comment by adeelq** [comment]
@Obblesnatch Thanks for reporting this. We have added this to current sprint. We will update you when we have released this.

**Comment by Obblesnatch** [comment]
@adeelq Great! Thank you.
To give a bit more information, the problem occurred when using a template configured in Admin (override for the file-based template), and when there was a 'ç' in the subject line. The template would save without error, and the subject would display correctly in the grid, but when going back into the edit page the subject field was empty. Replacing the 'ç' with 'c' "fixed" the issue as well.

**Comment by sta1r** [comment]
@Obblesnatch apologies for the late notice, but this issue was resolved and shipped in [v6.4.13](https://github.com/dotmailer/dotmailer-magento-extension/releases/tag/v6.4.13).
