### ISSUE TITLE
Not All Campaigns are returned

### ISSUE THREAD

**Issue by pocallaghan** [dotmailer/dotmailer-magento-extension#313]
The `Dotdigitalgroup_Email_Model_Apiconnector_Client::getCampaigns` method makes a single request to `/v2/campaigns` according to the [developer documentation](https://developer.dotdigital.com/docs/get-all-campaigns)  this endpoint is limited to 1000 campaigns. If a dotmailer user sends a lot of campaigns, their abandon cart campaigns soon drop down the list and no longer get returned as part of the most recently 1000 campaigns, thus attempting to re-save the Abandoned Cart section of the Magento configuration becomes impossible.

**Comment by sta1r** [comment]
@pocallaghan Thank you for raising. We solved the same issue for Magento 2, but will now map to Magento 1 also. I'll report back when this is released.

**Comment by sta1r** [comment]
@pocallaghan Released in [6.4.20](https://github.com/dotmailer/dotmailer-magento-extension/releases/tag/v6.4.20).
