### ISSUE TITLE
SubheadingWithComment class not found

### ISSUE THREAD

**Issue by sergey-fedosimov** [dotmailer/dotmailer-magento-extension#317]
**Issue:**
`PHP Fatal error:  Class 'Dotdigitalgroup_Email_Block_Adminhtml_System_Dynamic_SubheadingWithComment' not found in /var/www/html/app/www/app/code/core/Mage/Core/Model/Layout.php on line 590`

Magento resolves 'ddg_automation/adminhtml_system_dynamic_subheadingwithcomment' to 'Dotdigitalgroup_Email_Block_Adminhtml_System_Dynamic_Subheadingwithcomment' and then try to find 'Dotdigitalgroup/Email/Block/Adminhtml/System/Dynamic/Subheadingwithcomment.php' instead of 'Dotdigitalgroup_Email_Block_Adminhtml_System_Dynamic_Subheading**W**ith**C**omment' and 'Dotdigitalgroup/Email/Block/Adminhtml/System/Dynamic/Subheading**W**ith**C**omment.php' respectively. This is correct behavior, and the file will find on a windows machine but not on Linux one due to Linux use file case sensitive mode.

**Solution:**
Rename the class to Dotdigitalgroup_Email_Block_Adminhtml_System_Dynamic_Subheadingwithcomment and the file to Subheadingwithcomment.php

**Comment by sta1r** [comment]
@sergey-fedosimov Thanks for flagging this issue. We've just pushed a fix to develop: https://github.com/dotmailer/dotmailer-magento-extension/commit/7fa42572e91cdb4ef1df822fcfddb20b4175e523. Please do use this - it's only one commit ahead of master, and and our next release now will be in January.
