### ISSUE TITLE
Connot add/edit Transactional Emails are installing v5.1.0

### ISSUE THREAD

**Issue by kush1960** [dotmailer/dotmailer-magento-extension#5]
I get error 500 after attempting to create new transactional emails or edit existing ones in the Magento admin System > Transactional Emails
This was working in v5.0.4.
Looking at the logs, this error gets thrown...
```exception 'Mage_Core_Exception' with message 'Invalid block type: ddg_automation/system_email_template_edit' in /chroot/home/pexwhole/prelaunch.pexwholesale.co.uk/html/app/Mage.php:595```

**Comment by cdiacon** [comment]
Hi @kush1960 can you comment this lines for now in etc/config.xml 135line: 
```
<adminhtml>
                <rewrite>
                    <system_email_template_edit>ddg_automation/system_email_template_edit</system_email_template_edit>
                </rewrite>
            </adminhtml>
```

I'll see what is the exact problem that cause this and will come back.

**Comment by kush1960** [comment]
That fixed it for now. Thanks.
