### ISSUE TITLE
curl_setopt(): Disabling safe uploads is no longer supported

### ISSUE THREAD

**Issue by netstartergit** [dotmailer/dotmailer-magento-extension#66]
I am getting this error when running on PHP 7.0.2. 
Model/Apiconnector/Client.php::postAddressBookContactsImport
```
curl_setopt($ch, CURLOPT_SAFE_UPLOAD, false);
```
This function does not supports in PHP 7.

**Comment by cdiacon** [comment]
@netstartergit are sure you have a running Magento1 on php7???

**Comment by netstartergit** [comment]
@cdiacon sorry, my bad. this should go under M2 git. Closing & opening new issue in M2 git.
https://github.com/dotmailer/dotmailer-magento2-extension/issues/15

**Comment by manezaf8** [comment]
What is the fix for magento 1?
