### ISSUE TITLE
Customer class set data should contain key

### ISSUE THREAD

**Issue by adeelq** [dotmailer/dotmailer-magento-extension#76]
Customer class set data should contain key as well as value

**Comment by adeelq** [comment]
no an issue

**Comment by cdiacon** [comment]
I don't see the problem with csv files for any custom attrubutes mapped?!?

**Comment by adeelq** [comment]
I also think this is not a problem somehow for readability i think we should do this. it wont do anything bad.

**Comment by adeelq** [comment]
@cdiacon so shall i revert this or keep this. i'm ok either way.

**Comment by cdiacon** [comment]
avoid changes if we don't improve anything.

**Comment by adeelq** [comment]
ok got it gonna revert it
