### ISSUE TITLE
System.xml fields hidden when store views are selected

### ISSUE THREAD

**Issue by Obblesnatch** [dotmailer/dotmailer-magento-extension#78]
There are certain fields which should be (and are marked as) available on the store view scope, but the section and/or group are marked as only show for website and show for default. If the parent is hidden, the child won't be seen. This is especially important with abandoned carts (`<connector_lost_baskets>`) as we were unable to select different abandoned cart trigger emails for our multilingual site.

**Comment by cdiacon** [comment]
Hi @Obblesnatch this was already changed for abandoned carts, it's on testing branch and will be merged on the next release.
