### ISSUE TITLE
Single Orders - JsonValueIncompatibleWithSchema

### ISSUE THREAD

**Issue by bsstaveley** [dotmailer/dotmailer-magento-extension#81]
When we create and attempt to import "Single Orders" this error is being displayed on a number of sites. My assumption is we are altering the JSON type/schema between bulk and single inserts.

JsonValueIncompatibleWithSchema. A value named 'custom' of type List already exists in this collection and new values must be of this type. ERROR_TRANSACTIONAL_DATA_VALIDATION_FAILED

**Comment by adeelq** [comment]
On which testing site did you get it @bsstaveley

**Comment by adeelq** [comment]
@bsstaveley any chance i can get the JSON for the error request. I'm having difficulty reproducing this. The custom type is array which i believe is tyoe list in DM. So not sure why this error. So it can be great if i can get JSON for the error
