### ISSUE TITLE
Connector Status Page in Admin Area complaints about missing dotmailer extension files

### ISSUE THREAD

**Issue by technik-vitafy** [dotmailer/dotmailer-magento-extension#9]
This occurs in version 5.1.0. Is this a false positive?

![screen shot 2015-12-03 at 09 39 07](https://cloud.githubusercontent.com/assets/13380473/11555614/e16cdbe0-99a1-11e5-8561-ef13b85a83e9.png)

**Comment by cdiacon** [comment]
Thanks @technik-vitafy and you should consider this true positive now ;)
